"""Adicionado itens no pedido

Revision ID: 6d7b81b412cd
Revises: 8a7fbcb318c8
Create Date: 2026-05-20 09:32:16.650019

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '6d7b81b412cd'
down_revision: str | Sequence[str] | None = '8a7fbcb318c8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
